name: oblig3_gh_actions
run-name: ${{ github.actor }} sin første GitHub Actions til oblig3.
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'

      - name: Build
        run: mvn --batch-mode -DskipTests package -f /home/runner/work/leapyear/pom.xml

      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      - name: Test rapport
        uses: dorny/test-reporter@v1
        if: always()
        with: 
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
